import { SchemaField, TableSchema } from "./types";

/**
 * ai_profiles.tbl / *-aip.tbm schema.
 *
 * Entry key is confirmed (fso-table-fields-reference project memory, `ai_profiles.cpp`)
 * to be `$Profile Name:`, NOT `$Name:` - the one table in this catalog that differs from
 * every other table's `$Name:` convention. An earlier version of this schema used
 * "Name", which meant the order validator's `entryKeyFieldSeen` guard silently skipped
 * every real ai_profiles.tbl entirely (never matched, never flagged anything).
 *
 * Every other field is marked `unordered` (see `SchemaField`'s doc comment in
 * schemas/types.ts), not left as a plain ordered name: `ai_profiles.cpp`'s own source
 * comment says outright that "they're all optional and can be in any order", and the
 * parser is written accordingly (a retry loop that re-scans for the next matching field,
 * rather than one straight-through sequential pass like ships.tbl's). Order-checking them
 * instead would have swapped one kind of noise for a worse one - "unrecognized field"
 * false positives for a real, comprehensive Blue Planet ai_profiles.tbm (398 of them)
 * traded for "out of order" false positives on the exact same file, since a real file is
 * free to use a different order than any single list this schema could assert.
 */
const UNORDERED_FIELD_NAMES: string[] = [
  "Default Profile",
    "Player Afterburner Recharge Scale",
    "Max Beam Friendly Fire Damage",
    "Max Weapon Friendly Fire Damage",
    "Max Weapon Self Damage",
    "Player Countermeasure Life Scale",
    "AI Countermeasure Firing Chance",
    "AI In Range Time",
    "AI Always Links Ammo Weapons",
    "AI Maybe Links Ammo Weapons",
    "Primary Ammo Burst Multiplier",
    "AI Always Links Energy Weapons",
    "AI Maybe Links Energy Weapons",
    "Max Missles Locked on Player",
    "Max Missiles Locked on Player",
    "Max Player Attackers",
    "Max Incoming Asteroids",
    "Player Damage Factor",
    "AI Damage Reduction to Player Hull",
    "Player Subsys Damage Factor",
    "AI Damage Reduction to Player Subsys",
    "Player Damage Inflicted Factor",
    "Predict Position Delay",
    "AI Shield Manage Delay",
    "AI Shield Manage Delays",
    "Friendly AI Fire Delay Scale",
    "Hostile AI Fire Delay Scale",
    "Friendly AI Secondary Fire Delay Scale",
    "Hostile AI Secondary Fire Delay Scale",
    "AI Turn Time Scale",
    "Glide Attack Percent",
    "Circle Strafe Percent",
    "Glide Strafe Percent",
    "Random Sidethrust Percent",
    "Stalemate Time Threshold",
    "Stalemate Distance Threshold",
    "Player Shield Recharge Scale",
    "Player Weapon Recharge Scale",
    "Max Turret Target Ownage",
    "Max Turret Player Ownage",
    "Percentage Required For Kill Scale",
    "Percentage Required For Assist Scale",
    "Percentage Awarded For Capship Assist",
    "Repair Penalty",
    "Delay Before Allowing Bombs to Be Shot Down",
    "Chance AI Has to Fire Missiles at Player",
    "Max Aim Update Delay",
    "Turret Max Aim Update Delay",
    "Player Autoaim FOV",
    "Detail Distance Multiplier",
    "big ships can attack beam turrets on untargeted ships",
    "smart primary weapon selection",
    "smart secondary weapon selection",
    "smart shield management",
    "smart afterburner management",
    "free afterburner use",
    "allow rapid secondary dumbfire",
    "huge turret weapons ignore bombs",
    "don't insert random turret fire delay",
    "hack improve non-homing swarm turret fire accuracy",
    "shockwaves damage small ship subsystems",
    "navigation subsystem governs warpout capability",
    "check communications for non-player ships",
    "ignore lower bound for minimum speed of docked ship",
    "disable linked fire penalty",
    "disable player secondary doublefire",
    "disable ai secondary doublefire",
    "disable weapon damage scaling",
    "use additive weapon velocity",
    "use newtonian dampening",
    "include beams for kills and assists",
    "score kills based on damage caused",
    "score assists based on damage caused",
    "allow event and goal scoring in multiplayer",
    "fix linked primary weapon decision bug",
    "fix ramming stationary targets bug",
    "prevent turrets targeting too distant bombs",
    "smart subsystem targeting for turrets",
    "fix heat seekers homing on stealth ships bug",
    "multi allow empty primaries",
    "multi allow empty secondaries",
    "allow turrets target weapons freely",
    "use only single fov for turrets",
    "allow vertical dodge",
    "force beam turrets to use normal fov",
    "fix ai class bug",
    "turrets ignore targets radius in range checks",
    "no extra collision avoidance vs player",
    "perform fewer checks for death screams",
    "advanced turret fov edge checks",
    "require turrets to have target in fov",
    "all ships manage shields",
    "ai aims from ship center",
    "allow primary link at mission start",
    "allow beams to damage bombs",
    "disable weapon damage scaling for player",
    "countermeasures affect aspect seekers",
    "ai guards specific ship in wing",
    "support don't add primaries",
    "max allies rearming threshold",
    "firing requires exact los",
    "exact los minimum detection radius",
    "fighterbay arrivals use carrier orientation",
    "fighterbay departures use carrier orientation",
    "debris damage respects 'big damage' flag",
    "don't limit change in speed due to physics whack",
    "guards ignore protected attackers",
    "ai path mode",
    "no warp camera",
    "fix ai path order bug",
    "strict turret-tagged-only targeting",
    "aspect bomb invulnerability fix",
    "glide decay requires thrust",
    "ai can slow down when attacking big ships",
    "use actual primary range",
    "override radius for subsystem path points",
    "use POF radius for subsystem path points",
    "bay arrive speed multiplier",
    "bay depart speed multiplier",
    "perform less checks for death screams",
    "allow primary link delay",
    "lead indicator second-order prediction factor",
    "ships with no shields can manage ETS",
    "no directional bias for missile and ship turning",
    "respect ship axial turnrate differences",
    "any ship with no shields can manage ETS",
    "fighters/bombers with no shields can manage ETS",
    "ships playing dead don't manage ETS",
    "better combat collision avoidance for fightercraft",
    "better guard collision avoidance for fightercraft",
    "improved missile avoidance for fightercraft",
    "friendly ships use AI profile countermeasure chance",
    "unify usage of AI profile countermeasure chance",
    "improved subsystem attack pathing",
    "fixed ship-weapon collisions",
    "AI secondary range awareness",
    "no shield damage from ship collisions",
    "reset last_hit_target_time for player hits",
    "turret target recheck time",
    "prevent negative turret ammo",
    "fix keep-safe-distance",
    "AI ignores aspect lock for leading",
    "fix good-rearm-time bug",
    "no continuous turn on attack",
    "remove-goal properly removes play-dead order",
    "bay arrivals not time limited",
    "use adjusted AI class autoscale",
    "carry shield difficulty scaling bug",
    "debris affected by physics whacks",
    "asteroids affected by physics whacks",
    "dynamic goals afterburn hard",
    "player orders afterburn hard",
    "hud squad messages use tactical disarm/disable",
    "align to target when guarding stationary ship",
    "rotation factor multiplier for player collisions",
    "fix avoid-shockwave bugs",
    "fix standard strafe",
    "fix ai target recovery",
    "standard strafe used more",
    "standard strafe triggers under this speed",
    "strafe distance from target bounding box",
    "strafe stops after time unhit",
    "strafe retreat collide time",
    "strafe retreat collide distance",
    "guard uses big-orbit for target radius above",
    "guard with big-orbit uses max speed percent",
    "attack-any idle circle distance",
    "unify usage of AI Shield Manage Delay",
    "fix AI shield management bug",
    "AI balances shields instead of directs when attacked",
    "disable AI transferring energy",
    "enable freespace 1 style missile behavior",
    "ETS uses ship class power output",
    "ETS energy same regardless of system presence",
    "don't issue form-on-wing goals at mission start",
    "default form-on-wing priority",
    "do not clear goals when running form-on-wing",
    "do not clear goals when running stay-still",
    "do not set override when assigning form-on-wing",
    "purge player-issued form-on-wing after subsequent order",
    "cancel future waves of any wing launched from an exited ship",
    "ships intercept mines",
    "fix 'ignore if dead' flag",
    "no collision avoidance for kamikaze fighters",
    "fix big ship waypoint completion",
    "fix shockwave expiring before dealing damage",
    "fix fighter/bomber AI recovers after engines repaired",
];

export const aiProfilesSchema: TableSchema = {
  name: "ai_profiles.tbl",
  fileMatch: [/(^|[\\/])ai_profiles\.tbl$/i, /-aip\.tbm$/i],
  sectionNames: ["AI Profiles"],
  entryKeyField: "Profile Name",
  fields: [
    "Profile Name",
    "Description",
    ...UNORDERED_FIELD_NAMES.map((name): SchemaField => ({ name, unordered: true })),
  ],
};
