import { TableSchema } from "./types";

/**
 * weapons.tbl / *-wep.tbm schema.
 *
 * fieldOrder below is a mechanical, in-source-order extraction of every top-level
 * `$Field:` literal read by `parse_weapon()` in `code/weapon/weapons.cpp` (live-fetched
 * from the FSO GitHub source, not the wiki or guessed) - the same treatment ships.tbl's
 * schema got. `+`-sigil sub-fields are omitted entirely since schemaValidator.ts never
 * order-checks them anyway.
 *
 * Two earlier guessed entries, `Flash Impact Weapon Expl` and `HUD Target LOD`, were
 * CONFIRMED NOT TO EXIST anywhere in current weapons.cpp and have been removed - they
 * were flagging nothing (dead entries), but kept the schema looking more complete than
 * it was.
 *
 * Several modern/legacy field pairs only ever appear one-at-a-time in a real file (the
 * legacy one is parsed in an `else` branch when the modern one is absent) - both are
 * still included, adjacent, so whichever a real file uses lands in a sane relative
 * position: `Impact Effect`/`Impact Explosion` (+`Impact Explosion Radius`), `Piercing
 * Impact Effect`/`Piercing Impact Explosion`, `Muzzle Effect`/`Muzzleflash`. The
 * `$Piercing Impact Explosion:` field a real mod file was flagged for is exactly this
 * legacy fallback - it's real, not a typo, and is now in the schema.
 *
 * `Weapon Range` was previously listed as if a top-level `$` field; confirmed it's
 * actually `+Weapon Range:` (a sub-field, per a real mod file and live source
 * cross-check) and removed from this list, since `+`-sigil fields are never
 * order-checked here regardless.
 *
 * `Shockwave` (as a single block-opening field) does not exist; replaced with the real
 * flat `$Shockwave ...:`/`$Dinky shockwave:` field cluster.
 */
export const weaponsSchema: TableSchema = {
  name: "weapons.tbl",
  fileMatch: [/(^|[\\/])weapons\.tbl$/i, /-wep\.tbm$/i],
  sectionNames: ["Primary Weapons", "Secondary Weapons"],
  entryKeyField: "Name",
  fieldOrder: [
    "Name",
    "Alt name",
    "Subtype",
    "Turret Name",
    "Tech Model",
    "Selection Effect",
    "FS2 effect grid color",
    "FS2 effect scanline color",
    "FS2 effect grid density",
    "FS2 effect wireframe color",
    "HUD Image",
    "Model file",
    "POF target LOD",
    "Detail distance",
    "External Model File",
    "Submodel Rotation Speed",
    "Submodel Rotation Acceleration",
    "Light color",
    "Light radius",
    "Light intensity",
    "Collision Radius Override",
    "Mass",
    "Velocity",
    "Fire Wait",
    "Damage",
    "Damage Time",
    "Angle of Incidence Damage Multiplier",
    "Damage Multiplier over Lifetime Curve",
    "Damage Type",
    "Arm time",
    "Arm distance",
    "Arm radius",
    "Detonation Range",
    "Detonation Radius",
    "Proximity Radius",
    "MineInfo",
    "Flak Detonation Accuracy",
    "Flak Targeting Accuracy",
    "Untargeted Flak Range Penalty",
    "Shockwave damage",
    "Shockwave damage type",
    "Blast Force",
    "Inner Radius",
    "Outer Radius",
    "Shockwave Radius Multiplier over Lifetime Curve",
    "Shockwave Speed",
    "Shockwave Rotation",
    "Shockwave Rotation Is Relative To Parent",
    "Shockwave Model",
    "Shockwave Name",
    "Shockwave Sound",
    "Dinky shockwave",
    "Armor Factor",
    "Shield Factor",
    "Subsystem Factor",
    "Lifetime Min",
    "Lifetime Max",
    "Lifetime",
    "Energy Consumed",
    "Cargo Size",
    "Autoaim FOV",
    "Convergence",
    "Homing",
    "Homing Auto-Target Method",
    "Swarm",
    "Acceleration Time",
    "Velocity Inherit",
    "Free Flight Time",
    "Free Flight Speed",
    "Free Flight Speed Factor",
    "Gravity Const",
    "PreLaunchSnd",
    "LaunchSnd",
    "CockpitLaunchSnd",
    "ImpactSnd",
    "Disarmed ImpactSnd",
    "Shield ImpactSnd",
    "FlyBySnd",
    "AmbientSnd",
    "StartFiringSnd",
    "LoopFiringSnd",
    "LinkedLoopFiringSnd",
    "EndFiringSnd",
    "TrackingSnd",
    "LockedSnd",
    "InFlightSnd",
    "Model",
    "Rearm Rate",
    "Rearm Ammo Increment",
    "Disallow Support Rearm",
    "Pierce Objects",
    "Flags",
    "Trail",
    "Icon",
    "Anim",
    "Impact Effect",
    "Impact Explosion",
    "Impact Explosion Radius",
    "Shield Impact Explosion Radius",
    "Shield Impact Effect Radius",
    "Dinky Impact Effect",
    "Dinky Impact Explosion",
    "Dinky Impact Explosion Radius",
    "Piercing Impact Effect",
    "Piercing Impact Explosion",
    "Piercing Impact Radius",
    "Piercing Impact Velocity",
    "Piercing Impact Splash Velocity",
    "Piercing Impact Variance",
    "Piercing Impact Life",
    "Piercing Impact Particles",
    "Conditional Impact",
    "Inflight Effect",
    "Freeflight Effect",
    "Ignition Effect",
    "Homed Flight Effect",
    "Unhomed Flight Effect",
    "Muzzle Effect",
    "Muzzleflash",
    "EMP Intensity",
    "EMP Time",
    "Recoil Modifier",
    "Shudder Modifier",
    "Leech Weapon",
    "Leech Afterburner",
    "Vampiric Healing Factor",
    "Corkscrew",
    "Electronics",
    "Spawn Angle",
    "Spawn Minimum Angle",
    "Spawn Interval",
    "Spawn Chance",
    "Spawn Effect",
    "Spawn Aimed",
    "Spawn Aim Lead",
    "Lifetime Variation Factor When Child",
    "Local SSM",
    "Countermeasure",
    "BeamInfo",
    "Type 5 Beam Options",
    "Section",
    "Pspew",
    "Tag",
    "SSM",
    "FOF",
    "Firing Pattern",
    "Shots",
    "Cycle Multishot",
    "decal",
    "Impact Decal",
    "Transparent",
    "Weapon Hitpoints",
    "Armor Type",
    "Burst Shots",
    "Burst Delay",
    "Burst Flags",
    "Thruster Flame Effect",
    "Thruster Glow Effect",
    "Thruster Glow Radius Factor",
    "Failure Rate",
    "Animations",
    "Driven Animations",
    "substitute",
    "Score",
    "Custom data",
    "Custom Strings",
  ],
};
